[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/kernel.rs"
test = false
doctest = false
bench = false


[dependencies]
drivers = { path = "../drivers" }
